### ISSUE TITLE
RGenomeUtils loading

### ISSUE THREAD

**Issue by vreuter** [nsheff/project.init#4]
`projectInit` attempts to `devtools::load_all` of the `RGenomeUtils` package (conditioned on availability of non-null value for `"RGENOMEUTILS"` option). It seems like this should instead be a package installation, either from github or locally (via assumption of existence of something like `file.path(Sys.getenv("CODE"), "RGenomeUtils")`). It feels like a question of extent of external use of `project.init`...if it's only really being used internally, `load_all` seems OK, but for broader use an installation feels more appropriate. I guess I see both sides...

**Comment by nsheff** [comment]
moved to databio fork.
